---
abstract: 'send yourself a reminder'
author:
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110420'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: nag
requires:
  DateTime: 0
  DateTime::TimeZone: 0
  File::Temp: 0
  FileHandle: 0
  Getopt::Long::Descriptive: 0
  Gtk2::Notify: 0
  Modern::Perl: 0
  constant: 0
version: 0.002
